CREATE SCHEMA CUSTOMER;

CREATE TABLE CUSTOMER (
   ID BINARY(50) NOT NULL,
   FIRST_NAME VARCHAR(50) NOT NULL,
   LAST_NAME VARCHAR(20) NOT NULL,
   BIRTH_DATE  TIMESTAMP,
   GENDER VARCHAR(20) NOT NULL,
   PRIMARY KEY (id) 
);


CREATE TABLE ORDERS(
  ID BINARY(50) NOT NULL,
  CUSTOMER_ID BINARY(50) NOT NULL,
  ORDDER_DATE_TIME TIMESTAMP,
  ORDER_STATUS VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID) 
 )